
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Clion-2024.1/Clion/CLion 2024.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/Clion-2024.1/Clion/CLion 2024.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Clion-2024.1/Clion/CLion 2024.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Clion-2024.1/Clion/CLion 2024.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: D:/Zig-llvm/llvm/bin/clang.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is Clang, found in:
        E:/vmprojectcrontab/cmake-build-debug/CMakeFiles/3.28.1/CompilerIdC/a.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/Clion-2024.1/Clion/CLion 2024.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1182 (message)"
      - "D:/Clion-2024.1/Clion/CLion 2024.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:247 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "D:/Clion-2024.1/Clion/CLion 2024.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        
  -
    kind: "message-v1"
    backtrace:
      - "D:/Clion-2024.1/Clion/CLion 2024.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1182 (message)"
      - "D:/Clion-2024.1/Clion/CLion 2024.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:247 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "D:/Clion-2024.1/Clion/CLion 2024.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/Clion-2024.1/Clion/CLion 2024.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/Clion-2024.1/Clion/CLion 2024.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "E:/vmprojectcrontab/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-de6zlg"
      binary: "E:/vmprojectcrontab/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-de6zlg"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-O0"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'E:/vmprojectcrontab/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-de6zlg'
        
        Run Build Command(s): "D:/Clion-2024.1/Clion/CLion 2024.1/bin/ninja/win/x64/ninja.exe" -v cmTC_39019
        [1/2] D:\\Zig-llvm\\llvm\\bin\\clang.exe   -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -g -Xclang -gcodeview -MD -MT CMakeFiles/cmTC_39019.dir/CMakeCCompilerABI.c.obj -MF CMakeFiles\\cmTC_39019.dir\\CMakeCCompilerABI.c.obj.d -o CMakeFiles/cmTC_39019.dir/CMakeCCompilerABI.c.obj -c "D:/Clion-2024.1/Clion/CLion 2024.1/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeCCompilerABI.c"
        [2/2] C:\\WINDOWS\\system32\\cmd.exe /C "cd . && D:\\Zig-llvm\\llvm\\bin\\clang.exe -fuse-ld=lld-link -nostartfiles -nostdlib -O0 -D_DEBUG -D_DLL -D_MT -Xclang --dependent-lib=msvcrtd -g -Xclang -gcodeview -Xlinker /subsystem:console CMakeFiles/cmTC_39019.dir/CMakeCCompilerABI.c.obj -o cmTC_39019.exe -Xlinker /MANIFEST:EMBED -Xlinker /implib:cmTC_39019.lib -Xlinker /pdb:cmTC_39019.pdb -Xlinker /version:0.0     && cd ."
        
      exitCode: 0
...
